### PR TITLE
add 'include=line_items.physical_items.options' to add/update/get-cart requests

### PR DESCRIPTION
**Pull request by magicspon**

### CODE REVIEW

**Comment by jorgemasta** [comment]
Hi @magicspon ,

Can you describe a bit why do we want this?

BigCommerce documentation:
> `line_items.physical_items.options`: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return.


Should we update the `Cart` type if we add that new param? 
https://github.com/bigcommerce/storefront-data-hooks/blob/1245028d416b7998e253920130a9ad0adfc7d4b0/src/api/cart/index.ts#L110-L131

**Comment by magicspon** [comment]
hi @jorgemasta 

Without including this query, the product options aren't included.  I would have thought most people would want to be able to show the product options on the cart page.  

And, yup, we should probably update the Cart type

**Comment by jorgemasta** [comment]
Hey @magicspon, we need to think in a more general solution. Something like allowing product options to be passed from the hook. But it is certainly something interesting and we will work on it.

**Comment by magicspon** [comment]
@jorgemasta agreed.

**Comment by jorgemasta** [comment]
I have created a new PR to solve this from a different angle #68

**Pull request closed without merging**
