### PR TITLE
support: option_selections in useAddItem

### PR DESCRIPTION
**Pull request by magicspon**
https://github.com/bigcommerce/storefront-data-hooks/issues/2
https://github.com/bigcommerce/storefront-data-hooks/issues/12

### CODE REVIEW

**Comment by becomevocal** [comment]
@magicspon looks good!  Before merge, can you change the tabs to spaces and match the indentation?

**Comment by magicspon** [comment]
Bugger! Like a noob I make the edit directly in github.

just ran `npx prettier --ignore-path .gitignore src/**/*.ts`... looks like it's reformatted

**Comment by becomevocal** [comment]
👍

**Comment by magicspon** [comment]
awesome... thanks for that...

I've got another PR en route... I needed to update a few fetch requests to include the product options in the response object

**Pull request merged**
